### ISSUE TITLE
Questions: How to make sass prefix?

### ISSUE THREAD

**Issue by ahmetcaglayan** [RadValentin/postcss-prefix-selector#106]
I apply the following prefix setting for 'sass'. But the output is not what I want. The '/' signs remain. And the text color is not red. Do I need to add another setting? I added the prefix setting as in the document, but I seem to be missing something.

it's not working.

`prefix: "#single-spa-application:\\@kapital\\/dashboard"`

output still has '/' signs.

```
#single-spa-application:\@kapital\/dashboard .deneme {
    color: red;
}
```

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683359-7a1fcc9b-defd-46de-830f-e6ee02a10e9b.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683435-3ab7a3fc-fc47-4315-8408-87d6646d25f4.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683495-5f015c35-afa9-4883-afab-631e705088cc.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164683698-d497f280-066a-4a15-8da3-9145da56082f.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164684520-c0d4a21a-3de6-4d8d-a1ca-d5f19ad83e4b.png">

prefix i need

```
#single-spa-application:@kapital/dashboard .deneme {
    color: red;
}
```

but when I use it like this, **SassError: SassError: Expected identifier.** I get an error

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13018803/164704329-c5cf9e61-59cc-4077-9d1a-36a1c578de3a.png">

**Comment by RadValentin** [comment]
@ahmetcaglayan From what I can tell you're not escaping the special characters correctly, only a single `\` is needed, so the prefix option should be something like: `"#single-spa-application:\@kapital\/dashboard"`.

Also I'm not sure that it's a good idea to use `@` for a CSS selector, since it has special meaning, see [at-rules](https://sass-lang.com/documentation/at-rules/css)

**Comment by ahmetcaglayan** [comment]
When you delete the '@' sign, the situation is still the same. This time there is a problem with the '/' sign.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/13018803/164727004-1ff5596f-ba02-4f86-aba6-4a8991e55dc0.png">

**Comment by RadValentin** [comment]
@ahmetcaglayan I think the issue is that you're using characters which aren't recognised by the CSS parser. `@` and `:` are used for at-rules and pseudo elements. `\` and `/` aren't valid either. I tested this in plain CSS here: https://jsbin.com/mamadufolu/2/edit?html,css,output

I suggest using just the character types supported by CSS for selectors, see https://www.geeksforgeeks.org/which-characters-are-valid-in-css-class-names-selectors/

**Comment by ahmetcaglayan** [comment]
Actually it should be as you say. But it doesn't say so in the single spa document. Well, I didn't quite understand. But it automatically assigns this id for the div.

https://single-spa.js.org/docs/ecosystem-css#postcss-prefix-selector

**Comment by RadValentin** [comment]
@ahmetcaglayan I understand now, in the docs they set the prefix to:

```
"#single-spa-application\\:\\@org-name\\/project-name"
```

and then in the CSS output it will become

```
#single-spa-application\:\@org-name\/project-name
```
And because the characters are escaped, `\:`, `\@`, etc., it will work in plain CSS (https://jsbin.com/fequwemije/edit?html,css,output). The problem is that the SASS compiler doesn't like this kind of escaping.

![Screenshot 2022-04-23 at 17 32 11](https://user-images.githubusercontent.com/3300066/164912819-1affce3a-14df-4fa9-9160-67add5b7cc04.png)

I don't think I can help you. It looks like SASS doesn't like those escaped characters. I'd suggest using supported characters.

**Comment by RadValentin** [comment]
@ahmetcaglayan I was confused by the various escaped characters but I think it should work. You had it right initially, you just needed to escape the `:` character. Please try the following:

- set `prefix: "#single-spa-application\\:\\@kapital\\/dashboard"`
- in SASS and CSS the selector will be prefixed with `#single-spa-application\:\@kapital\/dashboard`
- The CSS selector above will match elements that have `id="single-spa-application:@kapital/dashboard`

Example here: https://codepen.io/valentin/pen/KKZLWej

**Comment by ahmetcaglayan** [comment]
sass doesn't like it. I guess the single spa needs to change the prefix it uses here.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/13018803/165030353-ed005583-6dba-4826-8b09-22627542a519.png">

**Comment by RadValentin** [comment]
@ahmetcaglayan Hmm, I don't see the escapes anymore, maybe you're not setting the prefix to `#single-spa-application\\:\\@kapital\\/dashboard`? In the original post the escapes were there

![image](https://user-images.githubusercontent.com/3300066/165033111-74653360-f156-4fa2-bd77-608c41aeb4be.png)
